title: Joe Kelly # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Developer student at Northcoders. 
  <br><br>
  I am confident with back-end development and have used Javascript extensively to complete projects. 
  Other software I am familar with include Express, Knex and Jest. I will be learning CSS and Html in
  the coming weeks.
  <br><br>
  <a href="https://www.linkedin.com/in/joe-kelly-ab4861138/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
