title: Joe Kelly # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Full stack developer student at Northcoders.<strong> 
  <br><br>
    I am confident with back-end development and have used <strong>Javascript<strong> extensively to complete projects. 
  Other software I am familar with include <strong>Express<strong>, <strong>Knex<strong> and <strong>Jest<strong>. I will be learning CSS and Html in
  the coming weeks.
  <br><br>
    <p style="color:blue">Education</p> Most recently I completed a masters degree in audio for video games at ThinkSpace Education,
  part of the University of Chichester. This is where I developed my interest in programming. Before this I 
  completed a BA in music at the University of Liverpool.
  <br><br>
    
    
  <a href="https://www.linkedin.com/in/joe-kelly-ab4861138/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-time-machine
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
